baseURL = 'https://kinqdathacker.github.io/'
locale = 'en-us'
title = 'The Innanet G4NG5T3R'
theme = "nightfall"

[params]
  user = "FLH"
  hostname = "kinqdathacker"
  displayDateFormat = "02.01.2006"

  [params.author]
    name = "Kinqdathacker"
    avatar = "/avatar.jpg"
    avatarSize = "size-m"
    avatarFirst = true

  [[params.social]]
    key = 0
    name = "github"
    url = "https://github.com/kinqdathacker"
    icon = "fa-brands fa-github"
    target = "_blank"
    aria = "GitHub Profile"

  [[params.social]]
    key = 1
    name = "twitter"
    url = "https://x.com/kinqdathacker"
    icon = "fa-brands fa-x-twitter"
    target = "_blank"
    aria = "X Profile"

[menu]
  [[menu.header]]
    name = "posts"
    title = "Posts"
    weight = 1
    url = "/posts/"


[pagination]
  pagerSize = 3
